<?php
$label = isset($this->context->label) ? $this->context->label . ':' : '';
$optionValuesDisabled = $this->context->optionValuesDisabled;
$optionValuesEnabled = $this->context->optionValuesEnabled;
$optionLabels = $this->context->optionLabels;
$optionNames = $this->context->optionNames;
$optionStates = $this->context->optionStates;
$keys = array_keys($optionNames);
$inputClass = isset($this->context->inputClass) ? $this->context->inputClass : '';
$ids = array_map('uniqid', $optionNames);
?>

<div class="form-row">
	<?php if (count($ids) == 1): ?>
		<label for="<?= $ids[0] ?>">
	<?php else: ?>
		<label>
	<?php endif ?>
		<?= $label ?>
	</label>
	<div class="input-wrapper">

		<?php foreach ($keys as $key): ?>
			<input type="hidden"
				<?php if ($inputClass): ?>
					class="<?= $inputclass ?>"
				<?php endif ?>
				name="<?= $optionNames[$key] ?>"
				value="<?= $optionValuesDisabled[$key] ?>"/>

			<label class="checkbox-wrapper" for="<?= $ids[$key] ?>">
				<input type="checkbox"
					id="<?= $ids[$key] ?>"
					name="<?= $optionNames[$key] ?>"
					<?php if ($optionStates[$key]): ?>
						checked="checked"
					<?php endif ?>
					value="<?= $optionValuesEnabled[$key] ?>"/>
				<span></span>

				<?= $optionLabels[$key] ?>
			</label>
		<?php endforeach ?>
	</div>
</div>
