<?php
$this->assets->setSubTitle('upload');
$this->assets->addStylesheet('post-upload.css');
$this->assets->addScript('post-upload.js');
$this->assets->addStylesheet('../lib/tagit/jquery.tagit.css');
$this->assets->addScript('../lib/tagit/jquery.tagit.js');
?>

<div id="inner-content">
	<div id="upload-step1">
		<div id="file-handler-wrapper">
			<input type=file multiple style="display: none"/>
			<div id="file-handler">
				Drop files here!<br/>
				Or just click on this box.
				<noscript>
					<br/>
					Note: this form needs Javascript to work.
				</noscript>
			</div>
		</div>

		<div id="url-handler-wrapper">
			<div id="url-handler">
				<div class="input-wrapper"><input placeholder="Alternatively, paste an URL here." name="url"/></div>
				<button class="submit" type="submit">Add URL</button>
			</div>
		</div>

		<div class="clear"></div>
	</div>

	<div id="upload-step2" data-redirect-url="<?= Core::getRouter()->linkTo(['PostController', 'listView']) ?>">
		<hr>

		<div id="hybrid-view">

		<div id="posts-wrapper">
			<table id="posts">
				<thead>
					<tr>
						<th class="checkbox">
							<label class="checkbox-wrapper">
								<input type="checkbox" name="select-all"/>
								<span></span>
							</label>
						</th>
						<th class="thumbnail"></th>
						<th class="tags">Tags</th>
						<th class="safety">Safety</th>
					</tr>
				</thead>

				<tbody>
				</tbody>

				<tfoot>
					<tr class="template">
						<td class="checkbox">
							<label class="checkbox-wrapper">
								<input type="checkbox"/>
								<span></span>
							</label>
						</td>
						<td class="thumbnail">
							<img src="<?= \Chibi\Util\Url::makeAbsolute('/media/img/pixel.gif') ?>" alt="Thumbnail"/>
						</td>
						<td class="tags">
						</td>
						<td class="safety">
							<div class="safety-template"></div>
						</td>
					</tr>
				</tfoot>
			</table>

			<ul id="post-ops">
				<li>
					<a href="#" class="btn move-up">Move selection up</a>
				</li>
				<li>
					<a href="#" class="btn move-down">Move selection down</a>
				</li>
				<li>
					<a href="#" class="btn remove">Remove selection</a>
				</li>
			</ul>

			<div id="the-submit-wrapper">
				<form action="<?= Core::getRouter()->linkTo(['PostController', 'uploadAction']) ?>" method="post">
					<button id="the-submit" class="submit" type="submit">Submit</button>
				</form>
			</div>
		</div>

		<div id="post-edit-form-wrapper">

			<p id="upload-error-alert" class="alert alert-error">
				Some kind of error
			</p>

			<p id="uploading-alert" class="alert alert-warning">
				Uploading in progress&hellip;
			</p>

			<div id="post-edit-form">
				<div class="thumbnail">
					<img src="<?= \Chibi\Util\Url::makeAbsolute('/media/img/pixel.gif') ?>" alt="Thumbnail"/>
				</div>

				<div class="form-wrapper">
					<form>
						<div class="form-row file-name">
							<label>File:</label>
							<div class="input-wrapper">
								<strong>filename.jpg</strong>
							</div>
						</div>

						<?php
							$safety = PostSafety::getAll();
							$context = new StdClass;
							$context->label = 'Safety';
							$context->name = 'safety';
							$context->optionValues = array_map(function($s) { return $s->toInteger(); }, $safety);
							$context->optionLabels = array_map(function($s) { return ucfirst($s->toDisplayString()); }, $safety);
							$context->activeOptionValue = PostSafety::Safe;
							$this->renderExternal('input-radioboxes', $context);

							$context = new StdClass;
							$context->label = 'Tags';
							$context->name = 'tags';
							$context->placeholder = 'Enter some tags&hellip;';
							$this->renderExternal('input-text', $context);

							$context = new StdClass;
							$context->label = 'Source';
							$context->name = 'source';
							$context->placeholder =' Where did you get this from? (optional)';
							$context->maxLength = Core::getConfig()->posts->maxSourceLength;
							$this->renderExternal('input-text', $context);

							if (Core::getConfig()->uploads->allowAnonymousUploads)
							{
								$context = new StdClass;
								$context->label = 'Anonymity';
								$context->optionNames = ['anonymous'];
								$context->optionValuesDisabled = ['0'];
								$context->optionValuesEnabled = ['1'];
								$context->optionLabels = ['Don\'t show my name in this post'];
								$context->optionStates = [false];
								$this->renderExternal('input-checkboxes', $context);
							}
						?>
					</form>
				</div>
			</div>
		</div>

		</div>

		<div id="lightbox">
			<img src="<?= \Chibi\Util\Url::makeAbsolute('/media/img/pixel.gif') ?>" alt="Preview">
		</div>
	</div>
</div>
