<?php
$post = $this->context->transport->post;
$this->assets->setPageThumbnail($post->getThumbnailUrl());
?>

<?php if ($post->getType()->toInteger() == PostType::Image): ?>

	<img alt="<?= $post->getName() ?>" src="<?= $post->getContentUrl() ?>"/>

<?php elseif ($post->getType()->toInteger() ==  PostType::Flash): ?>

	<object
		type="<?= $post->getMimeType() ?>"
		width="<?= $post->getImageWidth() ?>"
		height="<?= $post->getImageHeight() ?>"
		data="<?= $post->getContentUrl() ?>">

		<param name="wmode" value="opaque"/>
		<param name="movie" value="<?= $post->getContentUrl() ?>"/>

	</object>

<?php elseif ($post->getType()->toInteger() == PostType::Youtube): ?>

	<iframe src="//www.youtube.com/embed/<?= $post->getFileHash() ?>?wmode=opaque" allowfullscreen>
	</iframe>

<?php elseif ($post->getType()->toInteger() == PostType::Video): ?>

	<video controls>
		<source
			type="<?= $post->getMimeType() ?>"
			src="<?= $post->getContentUrl() ?>"/>

		Your browser doesn't support HTML5 &lt;video&gt; tag.
	</video>

<?php endif ?>
