<?php
$this->assets->addStylesheet('post-list.css');
$this->assets->addScript('post-list.js');

if (isset($this->context->source)
	and $this->context->source == 'mass-tag'
	and Access::check(new Privilege(Privilege::MassTag)))
{
	$this->renderExternal('tag-mass-tag');
}
?>

<?php if (!empty($this->context->transport->message)): ?>
	<?php $this->renderExternal('message') ?>
<?php elseif (empty($this->context->transport->posts)): ?>
	<p class="alert alert-warning">No posts to show.</p>
<?php else: ?>
	<div class="posts-wrapper">
		<div class="posts paginator-content">
			<?php foreach ($this->context->transport->posts as $post): ?>
				<?php $this->context->post = $post ?>
				<?php $this->renderExternal('post-small') ?>
			<?php endforeach ?>
		</div>
		<div class="clear"></div>
	</div>

	<?php $this->renderExternal('paginator') ?>
<?php endif ?>
