<form method="post"
	action="<?= \Chibi\Router::linkTo(
		['PostController', 'editAction'],
		['identifier' => $this->context->transport->post->getId()]) ?>"
	enctype="multipart/form-data"
	class="edit-post">

	<h1>edit post</h1>

	<input type="hidden"
		name="edit-token"
		id="edit-token"
		value="<?= htmlspecialchars($this->context->transport->post->getEditToken()) ?>"/>

	<?php
		if (Access::check(new Privilege(
			Privilege::EditPostSafety,
			Access::getIdentity($this->context->transport->post->getUploader()))))
		{
			$safety = PostSafety::getAll();

			$context = new StdClass;
			$context->label = 'Safety';
			$context->name = 'safety';
			$context->optionValues = array_map(function($s) { return $s->toInteger(); }, $safety);
			$context->optionLabels = array_map(function($s) { return ucfirst($s->toDisplayString()); }, $safety);
			$context->activeOptionValue = $this->context->transport->post->getSafety()->toInteger();
			$this->renderExternal('input-radioboxes', $context);
		}

		if (Access::check(new Privilege(
			Privilege::EditPostTags,
			Access::getIdentity($this->context->transport->post->getUploader()))))
		{
			$context = new StdClass;
			$context->label = 'Tags';
			$context->name = 'tags';
			$context->placeholder = 'Enter some tags&hellip;';
			$context->value = join(',', array_map(
				function($tag)
				{
					return htmlspecialchars($tag->getName());
				},
				$this->context->transport->post->getTags()));
			$this->renderExternal('input-text', $context);
		}

		if (Access::check(new Privilege(
			Privilege::EditPostSource,
			Access::getIdentity($this->context->transport->post->getUploader()))))
		{
			$context = new StdClass;
			$context->label = 'Source';
			$context->name = 'source';
			$context->value = htmlspecialchars($this->context->transport->post->getSource());
			$this->renderExternal('input-text', $context);
		}

		if (Access::check(new Privilege(
			Privilege::EditPostRelations,
			Access::getIdentity($this->context->transport->post->getUploader()))))
		{
			$context = new StdClass;
			$context->label = 'Relations';
			$context->name = 'relations';
			$context->placeholder = 'id1,id2,&hellip;';
			$context->value = join(',', array_map(
				function($post)
				{
					return $post->getId();
				},
				$this->context->transport->post->getRelations()));
			$this->renderExternal('input-text', $context);
		}

		if (Access::check(new Privilege(
			Privilege::EditPostContent,
			Access::getIdentity($this->context->transport->post->getUploader()))))
		{
			$context = new StdClass;
			$context->label = 'File';
			$context->name = 'url';
			$context->placeholder = 'Some URL&hellip;';
			$this->renderExternal('input-text', $context);

			$context = new StdClass;
			$context->name = 'file';
			$this->renderExternal('input-file', $context);
		}

		if (Access::check(new Privilege(
			Privilege::EditPostThumbnail,
			Access::getIdentity($this->context->transport->post->getUploader()))))
		{
			$context = new StdClass;
			$context->name = 'thumbnail';
			$context->label = 'Thumb';
			if ($this->context->transport->post->hasCustomThumbnail())
				$context->additionalInfo = '(Currently using custom thumb)';
			$this->renderExternal('input-file', $context);
		}
	?>

	<div class="form-row">
		<label></label>
		<button class="submit" type="submit">Submit</button>
	</div>
</form>
