<?php
$this->assets->setSubTitle('posts');
$searchQuery = isset($this->context->transport->searchQuery)
	? htmlspecialchars($this->context->transport->searchQuery)
	: '';

$parser = PostSearchService::getParser();
$newSearchQuery = PostSearchService::getParser()->removeTokenFromSearchString(
	$searchQuery,
	['favmin:1', 'scoremin:1', 'order:random']);

$tabs = [];
$activeTab = 0;
if (Access::check(new Privilege(Privilege::ListPosts)))
{
	$tabs []= [
		'title' => 'All posts',
		'active' => function() { return true; },
		'link' => Core::getRouter()->linkTo(
			['PostController', 'listView'],
			!trim($newSearchQuery) ? [] : ['query' => $newSearchQuery])];

	$tabs []= [
		'title' => 'Random',
		'active' => function() use ($searchQuery) { return strpos($searchQuery, 'order:random') !== false; },
		'link' => Core::getRouter()->linkTo(
			['PostController', 'listView'],
			['query' => $parser->addTokenToSearchString($newSearchQuery, 'order:random')])];

	$tabs []= [
		'title' => 'Favorites',
		'active' => function() use ($searchQuery) { return strpos($searchQuery, 'favmin:1') !== false; },
		'link' => Core::getRouter()->linkTo(
			['PostController', 'listView'],
			['query' => $parser->addTokenToSearchString($newSearchQuery, 'favmin:1')])];

	$tabs []= [
		'title' => 'Upvoted',
		'active' => function() use ($searchQuery) { return strpos($searchQuery, 'scoremin:1') !== false; },
		'link' => Core::getRouter()->linkTo(
			['PostController', 'listView'],
			['query' => $parser->addTokenToSearchString($newSearchQuery, 'scoremin:1')])];
}

if (Access::check(new Privilege(Privilege::MassTag)))
{
	$tabs []= [
		'title' => 'Mass tag',
		'active' => function() { return $this->context->source == 'mass-tag'; },
		'link' => Core::getRouter()->linkTo(['PostController', 'listView'], [
			'source' => 'mass-tag',
			'query' => $searchQuery,
			'page' => isset($this->context->transport->paginator)
				? $this->context->transport->paginator->page
				: 1])];
}

$activeTab = null;
foreach ($tabs as $key => $tab)
	if ($tab['active']())
		$activeTab = $key;
?>

<nav class="tabs">
	<ul>
		<?php foreach ($tabs as $key => $tab): ?>
			<?php
				$classes = [];
				$classes []= TextCaseConverter::convert($tab['title'],
					TextCaseConverter::BLANK_CASE,
					TextCaseConverter::SPINAL_CASE);
				if ($key == $activeTab)
					$classes []= 'selected';
			?>

			<li class="<?= join(' ', $classes) ?>">
				<a href="<?= $tab['link'] ?>">
					<?= $tab['title'] ?>
				</a>
			</li>
		<?php endforeach  ?>
	</ul>
</nav>

<div class="tab-content">
	<?php $this->renderExternal('post-list') ?>
</div>
