<?php
$this->assets->setSubTitle('upload');
$this->assets->addStylesheet('post-upload.css');
$this->assets->addScript('post-upload.js');
$this->assets->addStylesheet('../lib/tagit/jquery.tagit.css');
$this->assets->addScript('../lib/tagit/jquery.tagit.js');
?>

<div id="inner-content">
	<div id="upload-step1">
		<div id="file-handler-wrapper">
			<input type=file multiple style="display: none"/>
			<div id="file-handler">
				Drop files here!<br/>
				Or just click on this box.
				<noscript>
					<br/>
					Note: this form needs Javascript to work.
				</noscript>
			</div>
		</div>

		<div id="url-handler-wrapper">
			<div id="url-handler">
				<div class="input-wrapper"><input placeholder="Alternatively, paste an URL here." name="url"/></div>
				<button class="submit" type="submit">Add URL</button>
			</div>
		</div>

		<div class="clear"></div>
	</div>

	<div id="upload-step2" data-redirect-url="<?= Core::getRouter()->linkTo(['PostController', 'listView']) ?>">
		<hr>

		<div id="hybrid-view">

		<div id="posts-wrapper">
			<table id="posts">
				<thead>
					<tr>
						<th class="checkbox">
							<input type="checkbox" name="select-all"/>
						</th>
						<th class="thumbnail"></th>
						<th class="tags">Tags</th>
						<th class="safety">Safety</th>
					</tr>
				</thead>

				<tbody>
				</tbody>

				<tfoot>
					<tr class="template">
						<td class="checkbox">
							<input type="checkbox"/>
						</td>
						<td class="thumbnail">
							<img src="<?= \Chibi\Util\Url::makeAbsolute('/media/img/pixel.gif') ?>" alt="Thumbnail"/>
						</td>
						<td class="tags">
						</td>
						<td class="safety">
							<div class="safety-template"></div>
						</td>
					</tr>
				</tfoot>
			</table>

			<ul id="post-ops">
				<li>
					<a href="#" class="btn move-up">Move selection up</a>
				</li>
				<li>
					<a href="#" class="btn move-down">Move selection down</a>
				</li>
				<li>
					<a href="#" class="btn remove">Remove selection</a>
				</li>
			</ul>

			<div id="the-submit-wrapper">
				<form action="<?= Core::getRouter()->linkTo(['PostController', 'uploadAction']) ?>" method="post">
					<button id="the-submit" class="submit" type="submit">Submit</button>
				</form>
			</div>
		</div>

		<div id="post-edit-form-wrapper">

			<p id="upload-error-alert" class="alert alert-error">
				Some kind of error
			</p>

			<p id="uploading-alert" class="alert alert-warning">
				Uploading in progress&hellip;
			</p>

			<div id="post-edit-form">
				<div class="thumbnail">
					<img src="<?= \Chibi\Util\Url::makeAbsolute('/media/img/pixel.gif') ?>" alt="Thumbnail"/>
				</div>

				<div class="form-wrapper">
					<form>
						<div class="form-row file-name">
							<label>File:</label>
							<div class="input-wrapper">
								<strong>filename.jpg</strong>
							</div>
						</div>

						<div class="form-row safety">
							<label>Safety:</label>
							<div class="input-wrapper">
								<?php $checked = false ?>
								<?php foreach (PostSafety::getAll() as $safety): ?>
									<label>
										<input
											type="radio"
											name="safety"
											<?php if (!$checked): ?>
												checked="checked"
											<?php endif ?>
											value="<?= $safety->toInteger() ?>" />

										<?= ucfirst($safety->toDisplayString()) ?>

										<?php $checked = true ?>
									</label>
								<?php endforeach ?>
							</div>
						</div>

						<div class="form-row tags">
							<label>Tags:</label>
							<div class="input-wrapper">
								<input type="text" name="tags" placeholder="enter some tags&hellip;"/>
							</div>
						</div>

						<div class="form-row source">
							<label>Source:</label>
							<div class="input-wrapper">
								<input type="text"
									maxlength="<?= Core::getConfig()->posts->maxSourceLength ?>"
									name="source"
									placeholder="where did you get this from? (optional)"/>
							</div>
						</div>

						<?php if (Core::getConfig()->uploads->allowAnonymousUploads): ?>
							<div class="form-row anonymous">
								<label>Anonymity:</label>
								<div class="input-wrapper">
									<input type="hidden" name="anonymous" value="0"/>
									<label>
										<input type="checkbox" name="anonymous" value="1"/>
										Don't show my name in this post
									</label>
								</div>
							</div>
						<?php endif ?>
					</form>
				</div>
			</div>
		</div>

		</div>

		<div id="lightbox">
			<img src="<?= \Chibi\Util\Url::makeAbsolute('/media/img/pixel.gif') ?>" alt="Preview">
		</div>
	</div>
</div>
