<?php
$this->assets->setPageThumbnail(Core::getRouter()->linkTo(
	['PostController', 'thumbnailView'],
	['name' => $this->context->transport->post->getName()]));
$post = $this->context->transport->post;
?>

<?php if ($post->getType()->toInteger() == PostType::Image): ?>

	<img alt="<?= $post->getName() ?>"
		src="<?= Core::getRouter()->linkTo(
			['PostController', 'fileView'],
			['name' => $post->getName()]) ?>"/>

<?php elseif ($post->getType()->toInteger() ==  PostType::Flash): ?>

	<object
		type="<?= $post->getMimeType() ?>"
		width="<?= $post->getImageWidth() ?>"
		height="<?= $post->getImageHeight() ?>"
		data="<?= Core::getRouter()->linkTo(
			['PostController', 'fileView'],
			['name' => $post->getName()]) ?>">

		<param name="wmode" value="opaque"/>
		<param name="movie" value="<?= Core::getRouter()->linkTo(
			['PostController', 'fileView'],
			['name' => $post->getName()]) ?>"/>

	</object>

<?php elseif ($post->getType()->toInteger() == PostType::Youtube): ?>

	<iframe src="//www.youtube.com/embed/<?= $post->getFileHash() ?>?wmode=opaque" allowfullscreen>
	</iframe>

<?php elseif ($post->getType()->toInteger() == PostType::Video): ?>

	<video controls>
		<source
			type="<?= $post->getMimeType() ?>"
			src="<?= Core::getRouter()->linkTo(
				['PostController', 'fileView'],
				['name' => $post->getName()]) ?>">

		Your browser doesn't support HTML5 &lt;video&gt; tag.
	</video>

<?php endif ?>
