#!/bin/sh
set -e

docker build \
	--build-arg BASE_IMAGE=${IMAGE_NAME} \
	--file - \
	--tag ${IMAGE_NAME}-test \
	. <<'EOF'
ARG BASE_IMAGE
FROM ${BASE_IMAGE}
WORKDIR /opt/app
USER root
RUN apk --no-cache add \
		py3-pytest \
		py3-pytest-cov \
		postgresql \
	&& \
	pip3 install \
		--no-cache-dir \
		--disable-pip-version-check \
		pytest-pgsql \
		freezegun
USER app
ENV POSTGRES_HOST=x \
    POSTGRES_USER=x \
    POSTGRES_PASSWORD=x
CMD ["pytest", "szurubooru/", \
	"--cov-report=term-missing", "--cov=szurubooru", "--tb=short"]
EOF

docker run --rm -t ${IMAGE_NAME}-test

exit $?
