<?php
$this->assets->setSubTitle('logs (' . $this->context->transport->name . ')');
$this->assets->addStylesheet('logs.css');
?>

<?php if (empty($this->context->transport->lines)): ?>
	<p class="alert alert-warning">
		This log is empty. <a href="<?= Core::getRouter()->linkTo(['LogController', 'listView']) ?>">Go back</a>
	</p>
<?php else: ?>
	<?php
	$this->assets->addStylesheet('logs.css');
	$this->assets->addScript('logs.js');
	?>

	<form method="get"
		action="<?= Core::getRouter()->linkTo(
			['LogController', 'logView'],
			['name' => $this->context->transport->name]) ?>">

		Keep only lines that contain:

		<input type="text"
			name="query"
			value="<?= htmlspecialchars($this->context->transport->filter) ?>"
			placeholder="any text&hellip;"/>
	</form>

	<div class="paginator-content">
		<code><?= $this->context->transport->lines ?></code>
	</div>

	<?php $this->renderExternal('paginator') ?>
<?php endif ?>
