#!/usr/bin/env python3

'''
Script facade for direct execution with waitress WSGI server.
Note that szurubooru can be also run using ``python -m szurubooru``, when in
the repository's root directory.
'''

import argparse
import os.path
import sys
import waitress
from szurubooru.facade import app

def main():
    parser = argparse.ArgumentParser('Starts szurubooru using waitress.')
    parser.add_argument(
        '-p', '--port', type=int, help='port to listen on', default=6666)
    parser.add_argument('--host', help='IP to listen on', default='0.0.0.0')
    args = parser.parse_args()

    waitress.serve(app, host=args.host, port=args.port)

if __name__ == '__main__':
    main()
