<form action="<?php echo \Chibi\UrlHelper::route('auth', 'login') ?>" class="auth aligned" method="post">

	<div>
		<p>If you don't have an account yet,<br/><a href="<?php echo \Chibi\UrlHelper::route('auth', 'register'); ?>">click here</a> to create a new one.</p>
	</div>

	<div>
		<label class="left" for="name">User name:</label>
		<input id="name" name="name"/>
	</div>

	<div>
		<label class="left" for="password">Password:</label>
		<input type="password" id="password" name="password"/>
	</div>

	<?php if (isset($this->context->transport->errorMessage)): ?>
		<p class="alert alert-error">Error: <?php echo $this->context->transport->errorMessage ?></p>
	<?php endif ?>

	<div>
		<label class="left"></label>
		<button type="submit">Log in</button>
	</div>
</form>
