<?php
LayoutHelper::setSubTitle('authentication form');
LayoutHelper::addStylesheet('auth.css');
?>

<form action="<?php echo \Chibi\UrlHelper::route('auth', 'login') ?>" class="auth aligned" method="post">
	<div>
		<p>If you don't have an account yet,<br/><a href="<?php echo \Chibi\UrlHelper::route('user', 'registration'); ?>">click here</a> to create a new one.</p>
	</div>

	<div>
		<label class="left" for="name">User name:</label>
		<div class="input-wrapper"><input type="text" id="name" name="name"/></div>
	</div>

	<div>
		<label class="left" for="password">Password:</label>
		<div class="input-wrapper"><input type="password" id="password" name="password"/></div>
	</div>

	<div>
		<label class="left">&nbsp;</label>
		<div class="input-wrapper">
			<button class="submit" type="submit">Log in</button>
			&nbsp;
			<input type="hidden" name="remember" value="0"/>
			<label>
				<input type="checkbox" name="remember" value="1"/>
				Remember me
			</label>
		</div>
	</div>

	<?php $this->renderFile('message') ?>

	<input type="hidden" name="submit" value="1"/>

	<div class="help">
		<label class="left">&nbsp;</label>
		<div>
			<p>Problems logging in?</p>
			<ul>
				<li><a href="<?php echo \Chibi\UrlHelper::route('user', 'password-reset-proxy') ?>">I don't remember my password</a></li>
				<li><a href="<?php echo \Chibi\UrlHelper::route('user', 'activation-proxy') ?>">I haven't received activation e-mail</a></li>
				<li><a href="<?php echo \Chibi\UrlHelper::route('user', 'registration') ?>">I don't have an account</a></li>
			</ul>
		</div>
	</div>
</form>
