<?php if ($this->context->transport->success === true): ?>
	<p>Activation completed successfully.</p>
	<?php if ($this->context->transport->adminActivation): ?>
		<p>However, you still need to be approved by admin.</p>
	<?php endif ?>
<?php endif ?>

<?php if (isset($this->context->transport->errorMessage)): ?>
	<p class="alert alert-error"><?php echo $this->context->transport->errorMessage ?></p>
<?php endif ?>
