<?php
Assets::setSubTitle('authentication form');
Assets::addStylesheet('auth.css');
?>

<form
	method="post"
	action="<?= \Chibi\Router::linkTo(
		['AuthController', 'loginAction']) ?>"
	class="auth">

	<p>
		If you don't have an account yet,<br/>
		<a href="<?= \Chibi\Router::linkTo(['UserController', 'registrationView']); ?>">click here</a> to create a new one.
	</p>

	<div class="form-row">
		<label for="name">User name:</label>
		<div class="input-wrapper"><input type="text" id="name" name="name"/></div>
	</div>

	<div class="form-row">
		<label for="password">Password:</label>
		<div class="input-wrapper"><input type="password" id="password" name="password"/></div>
	</div>

	<div class="form-row">
		<label></label>
		<div class="input-wrapper">
			<button class="submit" type="submit">Log in</button>
			&nbsp;
			<input type="hidden" name="remember" value="0"/>
			<label><input type="checkbox" name="remember" value="1"/> Remember me</label>
		</div>
	</div>

	<?php \Chibi\View::render('message', $this->context) ?>

	<input type="hidden" name="submit" value="1"/>

	<div class="form-row help">
		<label></label>
		<div>
			<p>Problems logging in?</p>
			<ul>
				<li><a href="<?= \Chibi\Router::linkTo(['UserController', 'passwordResetProxyAction']) ?>">I don't remember my password</a></li>
				<li><a href="<?= \Chibi\Router::linkTo(['UserController', 'activationProxyAction']) ?>">I haven't received activation e-mail</a></li>
				<li><a href="<?= \Chibi\Router::linkTo(['UserController', 'registrationView']) ?>">I don't have an account</a></li>
			</ul>
		</div>
	</div>
</form>
