<?php
LayoutHelper::setSubTitle('comments');
?>

<?php if (empty($this->context->transport->comments)): ?>
	<p class="alert alert-warning">No comments to show.</p>
<?php else: ?>
	<?php
	LayoutHelper::addStylesheet('comment-list.css');
	LayoutHelper::addStylesheet('comment-small.css');
	LayoutHelper::addStylesheet('comment-edit.css');
	LayoutHelper::addScript('comment-edit.js');
	?>

	<div class="comments-wrapper">
		<div class="comments paginator-content">
			<?php
				$groups = [];
				$posts = [];
				$currentGroupPostId = null;
				$currentGroup = null;
				foreach ($this->context->transport->comments as $comment)
				{
					if ($comment->postId != $currentGroupPostId)
					{
						unset($currentGroup);
						$currentGroup = [];
						$currentGroupPostId = $comment->postId;
						$posts[$comment->postId] = $comment->getPost();
						$groups[] = &$currentGroup;
					}
					$currentGroup []= $comment;
				}
			?>
			<?php foreach ($groups as $group): ?>
				<div class="comment-group">
					<div class="post-wrapper">
						<?php $this->context->post = $posts[reset($group)->postId] ?>
						<?php echo $this->renderFile('post-small') ?>
					</div>
					<div class="comments">
						<?php foreach ($group as $comment): ?>
							<?php $this->context->comment = $comment ?>
							<?php echo $this->renderFile('comment-small') ?>
						<?php endforeach ?>
					</div>
					<div class="clear"></div>
				</div>
			<?php endforeach ?>
		</div>

		<?php $this->renderFile('paginator') ?>
	</div>
<?php endif ?>
