<?php
Assets::addStylesheet('comment-edit.css');
Assets::addScript('comment-edit.js');
?>

<form
	method="post"
	action="<?= \Chibi\Router::linkTo(
		['CommentController', 'editAction'],
		['id' => $this->context->transport->comment->id]) ?>"
	class="edit-comment">

	<h1>edit comment</h1>

	<div class="preview"></div>

	<div class="form-row text">
		<div class="input-wrapper">
			<textarea name="text" cols="50" rows="3"><?= $this->context->transport->comment->text ?></textarea>
		</div>
	</div>

	<input type="hidden" name="submit" value="1"/>

	<div class="form-row">
		<button name="sender" class="submit" type="submit" value="preview">Preview</button>&nbsp;
		<button name="sender" class="submit" type="submit" value="submit">Submit</button>
	</div>
</form>
