<?php
CustomAssetViewDecorator::setSubtitle('help');
CustomAssetViewDecorator::addStylesheet('index-help.css');

$tabs = $this->config->help->subTitles;
$firstTab = !empty($tabs) ? array_keys($tabs)[0] : null;
$showTabs = count($tabs) > 1;
?>

<?php if ($showTabs): ?>
	<nav class="tabs">
		<ul>
			<?php foreach ($tabs as $tab => $text): ?>
				<?php if ($tab == $this->context->tab): ?>
					<li class="selected <?php echo $tab ?>">
				<?php else: ?>
					<li class="<?php echo $tab ?>">
				<?php endif ?>
					<a href="<?php echo \Chibi\UrlHelper::route('index', 'help', $tab == $firstTab ? [] : ['tab' => $tab]) ?>">
						<?php echo $text ?>
					</a>
				</li>
			<?php endforeach ?>
		</ul>
	</nav>

	<div class="tab-content">
<?php endif ?>

<?php echo TextHelper::parseMarkdown(file_get_contents($this->context->path)) ?>

<?php if ($showTabs): ?>
	</div>
<?php endif ?>
