<?php
if (!empty($this->context->transport->errorMessage))
{
	\Chibi\HeadersHelper::set('Content-Type', 'text/plain; charset=utf-8');
	echo $this->context->transport->errorMessage;
}
else
{
	if (isset($this->context->transport->customFileName))
	{
		\Chibi\HeadersHelper::set(
			'Content-Disposition',
			'inline; filename="' . $this->context->transport->customFileName . '"');
	}

	\Chibi\HeadersHelper::set(
		'Content-Type',
		$this->context->transport->mimeType);

	readfile($this->context->transport->filePath);
	flush();
}
