<?php
CustomAssetViewDecorator::setSubTitle('logs (' . $name . ')');
?>

<?php if (empty($this->context->transport->lines)): ?>
	<p class="alert alert-warning">This log is empty. <a href="<?= \Chibi\UrlHelper::route('log', 'list') ?>">Go back</a></p>
<?php else: ?>
	<?php
	CustomAssetViewDecorator::addStylesheet('logs.css');
	CustomAssetViewDecorator::addScript('logs.js');
	?>

	<form action="<?= \Chibi\UrlHelper::route('log', 'view', ['name' => $this->context->transport->name]) ?>" method="get">
		Keep only lines that contain:

		<input type="text" name="query" value="<?= htmlspecialchars($this->context->transport->filter) ?>" placeholder="any text&hellip;"/>
	</form>

	<div class="paginator-content">
		<pre><?= $this->context->transport->lines ?></pre>
	</div>

	<?php $this->renderFile('paginator') ?>
<?php endif ?>
