<?php
if (!isset($this->context->transport->paginator))
	return;

$page = $this->context->transport->paginator->page;
$pageCount = $this->context->transport->paginator->pageCount;

$delta = 3;
$pagesVisible = [1, $pageCount];
$pagesVisible = array_merge($pagesVisible, range($page - $delta, $page + $delta));
$pagesVisible = array_filter($pagesVisible, function($x) use ($pageCount) { return $x >= 1 and $x <= $pageCount; });
$pagesVisible = array_unique($pagesVisible);
sort($pagesVisible, SORT_NUMERIC);

$finalPages = [$pagesVisible[0]];
for ($i = 1; $i < count($pagesVisible); $i ++)
{
	$prevPage = $pagesVisible[$i - 1];
	$subPage = $pagesVisible[$i];
	if ($subPage - $prevPage == 2)
		$finalPages []= $subPage - 1;
	elseif ($subPage - $prevPage > 2)
		$finalPages []= null;
	$finalPages []= $subPage;
}
$pagesVisible = $finalPages;

if (!function_exists('pageUrl'))
{
	function pageUrl($page)
	{
		$context = Core::getContext();
		$destination = $context->route->destination;
		$page = max(1, min($context->transport->paginator->pageCount, $page));
		$params = $context->route->arguments;
		$params['page'] = $page;
		return \Chibi\Router::linkTo($destination, $params);
	}
}
?>

<?php if (!empty($pagesVisible)): ?>
	<?php
	$this->assets->addStylesheet('paginator.css');
	if (Auth::getCurrentUser()->getSettings()->hasEnabledEndlessScrolling())
		$this->assets->addScript('paginator-endless.js');
	?>

	<nav class="paginator-wrapper">
		<ul class="paginator">
			<?php if ($page > 1): ?>
				<li class="prev">
			<?php else: ?>
				<li class="prev disabled">
			<?php endif ?>
				<a href="<?= pageUrl($page - 1) ?>">
					&laquo;
				</a>
			</li>

			<?php foreach ($pagesVisible as $subPage): ?>
				<?php if ($subPage === null): ?>
					<li>&hellip;</li>
				<?php else: ?>
					<?php if ($subPage == $page): ?>
						<li class="active">
					<?php else: ?>
						<li>
					<?php endif ?>
						<a href="<?= pageUrl($subPage) ?>">
							<?= $subPage ?>
						</a>
					</li>
				<?php endif ?>
			<?php endforeach ?>

			<?php if ($page < $pageCount): ?>
				<li class="next">
			<?php else: ?>
				<li class="next disabled">
			<?php endif ?>
				<a href="<?= pageUrl($page + 1) ?>">
					&raquo;
				</a>
			</li>
		</ul>
	</nav>
<?php endif ?>
