<?php if ($this->context->transport->success === true): ?>
	<p>Post created!</p>
<?php else: ?>

	<div id="sidebar">
		<div class="sidebar-unit">
			<h1>file upload</h1>
			<p>Use tags to describe uploaded images. Try to specify characters, their look and shows they are from.</p>
			<p>Set proper visibility setting if the image isn&rsquo;t safe for work or you&rsquo;re not sure it&rsquo;s 100% <span class="safety-sfw">safe</span>.</p>
			<p>Only registered users can view <span class="safety-sketchy">sketchy</span> or <span class="safety-nsfw">NSFW</span> content.</p>
			<p>Click submit when you&rsquo;re done.</p>
		</div>
	</div>

	<div id="inner-content">
		<div id="upload-step1">
			<input type=file multiple style="display: none"/>
			<div id="file-handler-wrapper">
				<div id="file-handler">
					Drop files here!<br>
					Or just click on this box.
				</div>
			</div>

			<div class="clear"></div>
		</div>

		<div id="upload-step2" data-redirect-url="<?php echo \Chibi\UrlHelper::route('post', 'list') ?>">
			<div class="posts">
			</div>

			<div class="submit-wrapper">
				<button id="the-submit" type="submit">Submit</button>
			</div>
		</div>

		<div id="post-template" class="post">
			<form action="<?php echo \Chibi\UrlHelper::route('post', 'upload') ?>" method="post">
				<p class="alert alert-error">Some kind of error</p>

				<a class="remove-trigger">
					remove <span>&times;</span>
				</a>

				<img class="thumbnail" src="<?php echo \Chibi\UrlHelper::absoluteUrl('/media/img/pixel.gif') ?>" alt="Thumbnail"/>
				<div>
					<div class="file-name">
						<label class="left">File:</label>
						<strong>filename.jpg</strong>
					</div>

					<div class="safety">
						<label class="left">Safety:</label>
						<label><input type="radio" name="safety" value="<?php echo PostSafety::Safe ?>" checked="checked"/> Safe for work</label>
						<label><input type="radio" name="safety" value="<?php echo PostSafety::Sketchy ?>"/> Sketchy</label>
						<label><input type="radio" name="safety" value="<?php echo PostSafety::Unsafe ?>"/> Not safe for work</label>
					</div>

					<div class="tags">
						<label class="left">Tags:</label>
						<input type="text" name="tags" placeholder="enter some tags&hellip;"/>
					</div>
				</div>
				<div class="clear"></div>
			</form>
		</div>

		<div id="upload-no-posts">
			<p class="alert alert-warning">Well, that&rsquo;s disappointing&hellip;</p>
			<p><a href="<?php echo \Chibi\UrlHelper::route('post', 'list') ?>">Back to post list</a> or <a href="<?php echo \Chibi\UrlHelper::route('post', 'upload') ?>">try uploading again</a>.</p>
		</div>
	</div>

<?php endif ?>
