<?php LayoutHelper::setPageThumb(\Chibi\UrlHelper::route('post', 'thumb', ['name' => $this->context->transport->post->name])) ?>
<?php $post = $this->context->transport->post ?>

<?php if ($post->type == PostType::Image): ?>

	<?php if (!empty($this->context->imageLink)): ?>
		<a href="<?php echo $this->context->imageLink ?>">
	<?php endif ?>

	<img src="<?php echo \Chibi\UrlHelper::route('post', 'retrieve', ['name' => $post->name]) ?>" alt="<?php echo $post->name ?>"/>

	<?php if (!empty($this->context->imageLink)): ?>
		</a>
	<?php endif ?>

<?php elseif ($post->type ==  PostType::Flash): ?>

	<object type="<?php echo $post->mimeType ?>" width="<?php echo $post->imageWidth ?>" height="<?php echo $post->imageHeight ?>" data="<?php echo \Chibi\UrlHelper::route('post', 'retrieve', ['name' => $post->name]) ?>">
		<param name="movie" value="<?php echo \Chibi\UrlHelper::route('post', 'retrieve', ['name' => $post->name]) ?>"/>
		<param name="wmode" value="opaque"/>
	</object>

<?php elseif ($post->type == PostType::Youtube): ?>

	<iframe style="width: 800px; height: 600px; border: 0;" src="//www.youtube.com/embed/<?php echo $post->fileHash ?>?wmode=opaque" allowfullscreen></iframe>

<?php endif ?>
