<?php
CustomAssetViewDecorator::setSubTitle('posts');

$tabs = [];
$activeTab = 0;
if (PrivilegesHelper::confirm(Privilege::ListPosts))
	$tabs []= ['All posts', \Chibi\UrlHelper::route('post', 'list')];

if (PrivilegesHelper::confirm(Privilege::ListPosts))
{
	$tabs []= ['Random', \Chibi\UrlHelper::route('post', 'random')];
	if ($this->context->route->simpleActionName == 'random')
		$activeTab = count($tabs) - 1;
}

if (PrivilegesHelper::confirm(Privilege::ListPosts))
{
	$tabs []= ['Favorites', \Chibi\UrlHelper::route('post', 'favorites')];
	if ($this->context->route->simpleActionName == 'favorites')
		$activeTab = count($tabs) - 1;
}

if (PrivilegesHelper::confirm(Privilege::ListPosts))
{
	$tabs []= ['Upvoted', \Chibi\UrlHelper::route('post', 'upvoted')];
	if ($this->context->route->simpleActionName == 'upvoted')
		$activeTab = count($tabs) - 1;
}

if (PrivilegesHelper::confirm(Privilege::MassTag))
{
	$tabs []= ['Mass tag', \Chibi\UrlHelper::route('post', 'list', [
		'source' => 'mass-tag',
		'query' => isset($this->context->transport->searchQuery) ? htmlspecialchars($this->context->transport->searchQuery) : '',
		'page' => isset($this->context->transport->paginator) ? $this->context->transport->paginator->page : 1])];
	if ($this->context->source == 'mass-tag')
		$activeTab = count($tabs) - 1;
}

?>

<nav class="tabs">
	<ul>
		<?php foreach ($tabs as $i => $tab): ?>
			<?php list($name, $url) = $tab ?>
			<?php if ($i == $activeTab): ?>
				<li class="selected <?= TextCaseConverter::convert($name, TextCaseConverter::BLANK_CASE, TextCaseConverter::SPINAL_CASE) ?>">
			<?php else: ?>
				<li class="<?= TextCaseConverter::convert($name, TextCaseConverter::BLANK_CASE, TextCaseConverter::SPINAL_CASE) ?>">
			<?php endif ?>
				<a href="<?= $url ?>">
					<?= $name ?>
				</a>
			</li>
		<?php endforeach  ?>
	</ul>
</nav>

<div class="tab-content">
	<?php $this->renderFile('post-list') ?>
</div>
