<div class="form-wrapper">
	<form class="aligned simple-action" method="post" action="<?php echo \Chibi\UrlHelper::route('tag', 'rename') ?>">
		<h1>rename tags</h1>
		<div>
			<label class="left" for="rename-source-tag">Source tag:</label>
			<div class="input-wrapper"><input class="autocomplete" type="text" type="text" name="source-tag" id="rename-source-tag" data-autocomplete-url="<?php echo \Chibi\UrlHelper::route('tag', 'list') ?>"/></div>
		</div>

		<div>
			<label class="left" for="rename-target-tag">Target tag:</label>
			<div class="input-wrapper"><input type="text" name="target-tag" id="rename-target-tag"/></div>
		</div>

		<input type="hidden" name="submit" value="1"/>

		<div>
			<label class="left">&nbsp;</label>
			<button type="submit">Rename!</button>
		</div>
	</form>
</div>
