<?php $max = max([0]+array_map(function($x) { return $x->getPostCount(); }, $this->context->transport->tags)); ?>
<div class="tags">
	<ul>
		<?php foreach ($this->context->transport->tags as $tag): ?>
			<li class="tag" title="<?php echo $tag->name ?> (<?php echo $tag->getPostCount() ?>)">
				<a href="<?php echo \Chibi\UrlHelper::route('post', 'list', ['query' => $tag->name]) ?>" style="opacity: <?php printf('%.02f', 0.25 + 0.75 *  log($tag->getPostCount()) / max(1, log(max(1, $max)))) ?>">
					<?php echo $tag->name . ' (' . $tag->getPostCount() . ')' ?>
				</a>
			</li>
		<?php endforeach ?>
	</ul>
</div>

<?php if (PrivilegesHelper::confirm(Privilege::MergeTags)): ?>
	<?php $this->renderFile('tag-merge') ?>
<?php endif ?>

<?php if (PrivilegesHelper::confirm(Privilege::RenameTags)): ?>
	<?php $this->renderFile('tag-rename') ?>
<?php endif ?>

<?php if (PrivilegesHelper::confirm(Privilege::MassTag)): ?>
	<?php $this->renderFile('tag-mass-tag') ?>
<?php endif ?>
