<?php
CustomAssetViewDecorator::setSubTitle('tags');
CustomAssetViewDecorator::addStylesheet('tag-list.css');

$tabs = [];
if (PrivilegesHelper::confirm(Privilege::ListTags)) $tabs['list'] = 'List';
if (PrivilegesHelper::confirm(Privilege::RenameTags)) $tabs['rename'] = 'Rename';
if (PrivilegesHelper::confirm(Privilege::MergeTags)) $tabs['merge'] = 'Merge';
if (PrivilegesHelper::confirm(Privilege::MassTag)) $tabs['mass-tag-redirect'] = 'Mass tag';
$showTabs = count($tabs) > 1;
?>

<?php if ($showTabs): ?>
	<nav class="tabs">
		<ul>
			<?php foreach ($tabs as $tab => $name): ?>
				<?php if ($this->context->route->simpleActionName == $tab): ?>
					<li class="selected <?= $tab ?>">
				<?php else: ?>
					<li class="<?= $tab ?>">
				<?php endif ?>
					<a href="<?= \Chibi\UrlHelper::route('tag', $tab) ?>">
						<?= $name ?>
					</a>
				</li>
			<?php endforeach  ?>
		</ul>
	</nav>

	<div class="tab-content">
<?php endif ?>

<?php if ($this->context->route->simpleActionName == 'merge'): ?>
	<?php $this->renderFile('tag-merge') ?>
<?php endif ?>

<?php if ($this->context->route->simpleActionName == 'rename'): ?>
	<?php $this->renderFile('tag-rename') ?>
<?php endif ?>

<?php if ($this->context->route->simpleActionName == 'list'): ?>
	<?php $this->renderFile('tag-list') ?>
<?php endif ?>

<?php if ($this->context->route->simpleActionName == 'mass-tag-redirect'): ?>
	<?php $this->renderFile('tag-mass-tag') ?>
<?php endif ?>

<?php if ($showTabs): ?>
	</div>
<?php endif ?>
