<?php if (isset($this->context->transport->message)): ?>
	<?php \Chibi\View::render('message', $this->context) ?>
<?php else: ?>
	<?php
	Assets::addStylesheet('auth.css');
	?>

	<form
		method="post"
		class="auth"
		autocomplete="off">

		<div class="form-row">
			<label>User:</label>
			<div class="input-wrapper">
				<input name="name" placeholder="Name or e-mail address" type="text"/>
			</div>
		</div>

		<input type="hidden" name="submit" value="1"/>

		<?php \Chibi\View::render('message', $this->context) ?>

		<div class="form-row">
			<label></label>
			<button class="submit" type="submit">Continue</button>
		</div>
	</form>
<?php endif ?>
