<form action="<?php echo \Chibi\UrlHelper::route('user', 'edit', ['name' => $this->context->transport->user->name]) ?>" method="post" class="edit" autocomplete="off">
	<?php if ($this->context->user->id == $this->context->transport->user->id): ?>
		<div class="form-row current-password">
			<label for="current-password">Current password:</label>
			<div class="input-wrapper"><input type="password" name="current-password" id="current-password" placeholder="Current password"/></div>
		</div>
		<hr>
	<?php endif ?>

	<?php if (PrivilegesHelper::confirm(Privilege::ChangeUserName, PrivilegesHelper::getIdentitySubPrivilege($this->context->transport->user))): ?>
		<div class="form-row nickname">
			<label for="name">Name:</label>
			<div class="input-wrapper"><input type="text" name="name" id="name" placeholder="New name&hellip;" value="<?php echo htmlspecialchars($this->context->suppliedName) ?>"/></div>
		</div>
	<?php endif ?>

	<?php if (PrivilegesHelper::confirm(Privilege::ChangeUserEmail, PrivilegesHelper::getIdentitySubPrivilege($this->context->transport->user))): ?>
		<div class="form-row email">
			<label for="name">E-mail:</label>
			<div class="input-wrapper"><input type="text" name="email" id="email" placeholder="New e-mail&hellip;" value="<?php echo htmlspecialchars($this->context->suppliedEmail) ?>"/></div>
		</div>
	<?php endif ?>

	<?php if (PrivilegesHelper::confirm(Privilege::ChangeUserPassword, PrivilegesHelper::getIdentitySubPrivilege($this->context->transport->user))): ?>
		<div class="form-row password1">
			<label for="password1">New password:</label>
			<div class="input-wrapper"><input type="password" name="password1" id="password1" placeholder="New password&hellip;" value="<?php echo htmlspecialchars($this->context->suppliedPassword1) ?>"/></div>
		</div>
		<div class="form-row password2">
			<label for="password2"></label>
			<div class="input-wrapper"><input type="password" name="password2" id="password2" placeholder="New password&hellip; (repeat)" value="<?php echo htmlspecialchars($this->context->suppliedPassword2) ?>"/></div>
		</div>
	<?php endif ?>

	<?php if (PrivilegesHelper::confirm(Privilege::ChangeUserAccessRank, PrivilegesHelper::getIdentitySubPrivilege($this->context->transport->user))): ?>
		<div class="form-row access-rank">
			<label for="access-rank">Access rank:</label>
			<div class="input-wrapper"><select name="access-rank" id="access-rank">
				<?php foreach (AccessRank::getAll() as $rank): ?>
					<?php if ($rank == AccessRank::Nobody) continue ?>
					<?php if (($this->context->suppliedAccessRank != '' and $rank == $this->context->suppliedAccessRank) or ($this->context->suppliedAccessRank == '' and $rank == $this->context->transport->user->accessRank)): ?>
						<option value="<?php echo $rank ?>" selected="selected">
					<?php else: ?>
						<option value="<?php echo $rank ?>">
					<?php endif ?>
						<?php echo TextHelper::camelCaseToHumanCase(AccessRank::toString($rank)) ?>
					</option>
				<?php endforeach ?>
			</select></div>
		</div>
	<?php endif ?>

	<input type="hidden" name="submit" value="1"/>

	<?php $this->renderFile('message') ?>

	<div class="form-row">
		<label></label>
		<button class="submit" type="submit">Submit</button>
	</div>
</form>
