<?php
LayoutHelper::setSubTitle('users');
LayoutHelper::addStylesheet('user-list.css');
LayoutHelper::addStylesheet('paginator.css');
if ($this->context->user->hasEnabledEndlessScrolling())
	LayoutHelper::addScript('paginator-endless.js');
?>

<nav class="sort-styles">
	<ul>
		<?php
		$filters =
		[
			'order:alpha,asc' => 'Sort A&rarr;Z',
			'order:alpha,desc' => 'Sort Z&rarr;A',
			'order:date,asc' => 'Sort old&rarr;new',
			'order:date,desc' => 'Sort new&rarr;old',
		];

		if ($this->config->registration->staffActivation)
			$filters['pending'] = 'Pending staff review';
		?>

		<?php foreach ($filters as $key => $text): ?>
			<?php if ($this->context->filter == $key): ?>
				<li class="active">
			<?php else: ?>
				<li>
			<?php endif ?>
				<a href="<?php echo \Chibi\UrlHelper::route('user', 'list', ['filter' => $key]) ?>"><?php echo $text ?></a>
			</li>
		<?php endforeach ?>
	</ul>
</nav>

<?php if (empty($this->context->transport->users)): ?>
	<p class="alert alert-warning">No users to show.</p>
<?php else: ?>
	<div class="users-wrapper">
		<div class="users paginator-content">
			<?php foreach ($this->context->transport->users as $user): ?>
				<div class="user">
					<a class="avatar" href="<?php echo \Chibi\UrlHelper::route('user', 'view', ['name' => $user->name]) ?>">
						<img src="<?php echo htmlspecialchars($user->getAvatarUrl(100)) ?>" alt="<?php echo $user->name ?>"/>
					</a>
					<div class="details">
						<h1>
							<a href="<?php echo \Chibi\UrlHelper::route('user', 'view', ['name' => $user->name]) ?>">
								<?php echo $user->name ?>
							</a>
						</h1>

						<div class="date-registered" title="<?php echo TextHelper::formatDate($user->joinDate, true) ?>">
							Registered: <?php echo TextHelper::formatDate($user->joinDate, false) ?>
						</div>

						<div class="post-count">
							Uploaded: <?php echo TextHelper::useDecimalUnits($user->getPostCount()) ?>
						</div>

						<div class="fav-count">
							Favorites: <?php echo TextHelper::useDecimalUnits($user->getFavoriteCount()) ?>
						</div>
					</div>
				</div>
			<?php endforeach ?>
		</div>
	</div>

	<?php $this->renderFile('paginator') ?>
<?php endif ?>
