<?php if ($this->context->transport->success === true): ?>
	<p class="alert alert-success">Congratulations, your account was created.
	<?php if (!empty($this->context->mailSent)): ?>
		<br>Please wait for activation e-mail.
		<?php if ($this->config->registration->staffActivation): ?>
			<br>After this, your registration must be confirmed by staff.
		<?php endif ?>
	<?php elseif ($this->config->registration->staffActivation): ?>
		<br>Your registration must be now confirmed by staff.
	<?php endif ?></p>
<?php else: ?>
	<form action="<?php echo \Chibi\UrlHelper::route('auth', 'register') ?>" class="auth aligned" method="post">
		<div>
			<p>Registered users can view more content,<br/>upload files and add posts to favorites.</p>
		</div>

		<div>
			<label class="left" for="name">User name:</label>
			<div class="input-wrapper"><input type="text" id="name" name="name" value="<?php echo $this->context->suppliedName ?>" placeholder="e.g. darth_vader" autocomplete="off"/></div>
		</div>

		<div>
			<label class="left" for="password1">Password:</label>
			<div class="input-wrapper"><input type="password" id="password1" name="password1" value="<?php echo $this->context->suppliedPassword1 ?>" placeholder="e.g. <?php echo str_repeat('&#x25cf;', 8) ?>" autocomplete="off"/></div>
		</div>

		<div>
			<label class="left" for="password2">Password (repeat):</label>
			<div class="input-wrapper"><input type="password" id="password2" name="password2" value="<?php echo $this->context->suppliedPassword2 ?>" placeholder="e.g. <?php echo str_repeat('&#x25cf;', 8) ?>" autocomplete="off"/></div>
		</div>

		<div>
			<label class="left" for="email">E-mail address:</label>
			<div class="input-wrapper"><input type="text" id="email" name="email" value="<?php echo $this->context->suppliedEmail ?>" placeholder="e.g. vader@empire.gov" autocomplete="off"/></div>
		</div>

		<div>
			<p id="email-info">Your e-mail will be used to show your <a href="http://gravatar.com/">Gravatar</a>.<br/>Leave blank for random Gravatar.</p>
		</div>

		<?php if (isset($this->context->transport->errorMessage)): ?>
			<div>
				<p class="alert alert-error">Error: <?php echo $this->context->transport->errorMessage ?></p>
			</div>
		<?php endif ?>

		<div>
			<label class="left"></label>
			<button type="submit">Register</button>
		</div>
	</form>
<?php endif ?>
