<form
	action="<?= \Chibi\Router::linkTo(
		['UserController', 'deleteAction'],
		['name' => $this->context->transport->user->name]) ?>"
	method="post"
	class="delete confirmable"
	autocomplete="off"
	data-confirm-text="Are you sure you want to delete your account?">

	<?php if (Auth::getCurrentUser()->id == $this->context->transport->user->id): ?>
		<div class="form-row current-password">
			<label for="current-password">Current password:</label>
			<div class="input-wrapper">
				<input type="password" name="current-password" id="current-password" placeholder="Current password"/>
			</div>
		</div>
	<?php endif ?>

	<input type="hidden" name="submit" value="1"/>

	<?php \Chibi\View::render('message', $this->context) ?>

	<div class="form-row">
		<label></label>
		<button class="submit" type="submit">Delete account</button>
	</div>
</form>
