<?php
$this->assets->setSubtitle('home');
$this->assets->addStylesheet('static-main.css');
?>

<div id="welcome">
	<h1><?= Core::getConfig()->appearance->title ?></h1>
	<p>
		<span>
			<?php printf('serving %d posts (%s)',
				$this->context->transport->postCount,
				TextHelper::useBytesUnits($this->context->transport->postSpaceUsage)) ?>
		</span>
	</p>
</div>

<?php if (!empty($this->context->featuredPost)): ?>
	<div class="body">
		<?php
			$this->context->transport->post = $this->context->featuredPost;
			$this->context->imageLink = Core::getRouter()->linkTo(
				['PostController', 'genericView'],
				['identifier' => $this->context->featuredPost->getId()]);
		?>

		<?php $this->renderExternal('post-file-render') ?>
	</div>

	<div class="footer">
		<div class="left">
			Tags:&nbsp;
			<ul class="tags">
				<?php $tags = $this->context->featuredPost->getTags() ?>
				<?php uasort($tags, function($a, $b) { return strnatcasecmp($a->getName(), $b->getName()); }) ?>
				<?php foreach ($tags as $tag): ?>
					<li>
						<a href="<?= Core::getRouter()->linkTo(['PostController', 'listView'], ['query' => $tag->getName()]) ?>">
							<?= $tag->getName() ?>
						</a>
					</li>
				<?php endforeach ?>
			</ul>
		</div>

		<div class="right">
			Featured
			<?php if ($this->context->featuredPostUser): ?>
				by
				<a href="<?= Core::getRouter()->linkTo(
					['UserController', 'genericView'],
					['identifier' => $this->context->featuredPostUser->getName()]) ?>">
					<?= $this->context->featuredPostUser->getName() ?>
				</a>,
			<?php endif ?>

			<?php $x = round((time() - $this->context->featuredPostUnixTime) / (24 * 3600.)) ?>
			<?php if ($x == 0): ?>
				today
			<?php elseif ($x == 1):?>
				yesterday
			<?php else: ?>
				<?php printf('%d days ago', $x) ?>
			<?php endif ?>
		</div>

		<div class="clear"></div>
	</div>

	<div class="clear"></div>
<?php endif ?>
