<form
	action="<?= \Chibi\Router::linkTo(
		['UserController', 'deleteAction'],
		['identifier' => $this->context->transport->user->getName()]) ?>"
	method="post"
	class="user-delete simple-action confirmable"
	autocomplete="off"
	data-confirm-text="Are you sure you want to delete your account?">

	<?php
		if (Auth::getCurrentUser()->getId() == $this->context->transport->user->getId())
		{
			$context = new StdClass;
			$context->label = 'Current password';
			$context->name = 'current-password';
			$context->placeholder = 'Current password';
			$this->renderExternal('input-password', $context);
		}
	?>

	<?php $this->renderExternal('message') ?>

	<div class="form-row">
		<label></label>
		<button class="submit" type="submit">Delete account</button>
	</div>
</form>
