<?php
$this->assets->addScript('user-edit.js');
?>

<form
	action="<?= \Chibi\Router::linkTo(
		['UserController', 'editAction'],
		['identifier' => $this->context->transport->user->getName()]) ?>"
	enctype="multipart/form-data"
	method="post"
	class="edit-user simple-action"
	autocomplete="off">

	<?php
		if (Auth::getCurrentUser()->getId() == $this->context->transport->user->getId())
		{
			$context = new StdClass;
			$context->label = 'Current password';
			$context->name = 'current-password';
			$context->placeholder = 'Current password';
			$this->renderExternal('input-password', $context);
			echo '<hr/>';
		}

		if (Access::check(new Privilege(
			Privilege::EditUserAvatar,
			Access::getIdentity($this->context->transport->user))))
		{
			$styles = UserAvatarStyle::getAll();
			$context = new StdClass;
			$context->name = 'avatar-style';
			$context->label = 'User picture';
			$context->optionValues = array_map(function($s) { return $s->toInteger(); }, $styles);
			$context->optionLabels = array_map(function($s) { return ucfirst($s->toDisplayString()); }, $styles);
			$context->activeOptionValue = $this->context->transport->user->getAvatarStyle()->toInteger();
			$context->inputClass = 'avatar-style';
			$this->renderExternal('input-radioboxes', $context);

			$context = new StdClass;
			$context->name = 'avatar-content';
			$context->inputClass = 'avatar-content';
			$this->renderExternal('input-file', $context);
		}

		if (Access::check(new Privilege(
			Privilege::EditUserName,
			Access::getIdentity($this->context->transport->user))))
		{
			$context = new StdClass;
			$context->label = 'Name';
			$context->name = 'name';
			$context->placeholder = 'New name&hellip;';
			$context->value = htmlspecialchars(InputHelper::get('name'));
			$this->renderExternal('input-text', $context);
		}

		if (Access::check(new Privilege(
			Privilege::EditUserEmail,
			Access::getIdentity($this->context->transport->user))))
		{
			$context = new StdClass;
			$context->label = 'E-mail';
			$context->name = 'email';
			$context->placeholder = 'New e-mail&hellip;';
			$context->value = htmlspecialchars(InputHelper::get('email'));
			$this->renderExternal('input-text', $context);
		}

		if (Access::check(new Privilege(
			Privilege::EditUserPassword,
			Access::getIdentity($this->context->transport->user))))
		{
			$context = new StdClass;
			$context->label = 'New password';
			$context->name = 'password1';
			$context->placeholder = 'New password&hellip;';
			$context->value = htmlspecialchars(InputHelper::get('password1'));
			$this->renderExternal('input-password', $context);

			$context = new StdClass;
			$context->name = 'password2';
			$context->placeholder = 'New password&hellip; (repeat)';
			$context->value = htmlspecialchars(InputHelper::get('password2'));
			$this->renderExternal('input-password', $context);
		}

		if (Access::check(new Privilege(
			Privilege::EditUserAccessRank,
			Access::getIdentity($this->context->transport->user))))
		{
			$accessRanks = array_filter(
				AccessRank::getAll(),
				function($ar)
				{
					return $ar->toInteger() != AccessRank::Nobody;
				});

			$context = new StdClass;
			$context->name = 'access-rank';
			$context->label = 'Access rank';
			$context->placeholder = 'New password&hellip; (repeat)';
			$context->optionValues = array_map(function($ar) { return $ar->toInteger(); }, $accessRanks);
			$context->optionLabels = array_map(function($ar) { return $ar->toDisplayString(); }, $accessRanks);
			$context->activeOptionValue = InputHelper::get('access-rank')
				?: $this->context->transport->user->getAccessRank()->toInteger();
			$this->renderExternal('input-select', $context);
		}

		$this->renderExternal('message');
	?>

	<div class="form-row">
		<label></label>
		<button class="submit" type="submit">Submit</button>
	</div>
</form>
