<?php
Assets::setSubTitle('tags');
Assets::addStylesheet('tag-list.css');

$tabs = [];
if (Access::check(new Privilege(Privilege::ListTags)))
	$tabs['list'] = ['List', 'listView'];

if (Access::check(new Privilege(Privilege::RenameTags)))
	$tabs['rename'] = ['Rename', 'renameView'];

if (Access::check(new Privilege(Privilege::MergeTags)))
	$tabs['merge'] = ['Merge', 'mergeView'];

if (Access::check(new Privilege(Privilege::MassTag)))
	$tabs['mass-tag-redirect'] = ['Mass tag', 'massTagRedirectAction'];

$showTabs = count($tabs) > 1;
?>

<?php if ($showTabs): ?>
	<nav class="tabs">
		<ul>
			<?php foreach ($tabs as $tab => $item): ?>
				<?php list ($name, $action) = $item ?>
				<?php if ($this->context->simpleActionName == $tab): ?>
					<li class="selected <?= $tab ?>">
				<?php else: ?>
					<li class="<?= $tab ?>">
				<?php endif ?>
					<a href="<?= \Chibi\Router::linkTo(['TagController', $action]) ?>">
						<?= $name ?>
					</a>
				</li>
			<?php endforeach  ?>
		</ul>
	</nav>

	<div class="tab-content">
<?php endif ?>

<?php if ($this->context->simpleActionName == 'merge'): ?>
	<?php \Chibi\View::render('tag-merge', $this->context) ?>
<?php endif ?>

<?php if ($this->context->simpleActionName == 'rename'): ?>
	<?php \Chibi\View::render('tag-rename', $this->context) ?>
<?php endif ?>

<?php if ($this->context->simpleActionName == 'list'): ?>
	<?php \Chibi\View::render('tag-list', $this->context) ?>
<?php endif ?>

<?php if ($this->context->simpleActionName == 'mass-tag-redirect'): ?>
	<?php \Chibi\View::render('tag-mass-tag', $this->context) ?>
<?php endif ?>

<?php if ($showTabs): ?>
	</div>
<?php endif ?>
