<div class="form-wrapper">
	<form method="post" action="<?= \Chibi\Router::linkTo(['TagController', 'mergeAction']) ?>">
		<h1>merge tags</h1>

		<?php
			$context = new StdClass;
			$context->name = 'source-tag';
			$context->label = 'Source tag';
			$context->inputClass = 'autocomplete';
			$this->renderExternal('input-text', $context);

			$context = new StdClass;
			$context->name = 'target-tag';
			$context->label = 'Target tag';
			$this->renderExternal('input-text', $context);

			$this->renderExternal('message');
		?>

		<div class="form-row">
			<label></label>
			<button class="submit" type="submit">Merge!</button>
		</div>
	</form>
</div>
