<div class="form-wrapper">
	<form method="post" action="<?= \Chibi\Router::linkTo(['TagController', 'mergeAction']) ?>">
		<h1>merge tags</h1>

		<div class="form-row">
			<label for="merge-source-tag">Source tag:</label>
			<div class="input-wrapper">
				<input class="autocomplete" type="text" name="source-tag" id="merge-source-tag"/>
			</div>
		</div>

		<div class="form-row">
			<label for="merge-target-tag">Target tag:</label>
			<div class="input-wrapper">
				<input class="autocomplete" type="text" name="target-tag" id="merge-target-tag"/>
			</div>
		</div>

		<?php $this->renderExternal('message') ?>

		<div class="form-row">
			<label></label>
			<button class="submit" type="submit">Merge!</button>
		</div>
	</form>
</div>
