<div class="form-wrapper">
	<form method="post"
		class="simple-action"
		action="<?= Core::getRouter()->linkTo(
			['PostController', 'listRedirectAction'],
			['source' => 'mass-tag']) ?>">

		<h1>mass tag</h1>

		<?php
			$context = new StdClass;
			$context->name = 'query';
			$context->label = 'Search query';
			$context->inputClass = 'autocomplete';
			if (isset($this->context->massTagQuery))
				$context->value = htmlspecialchars($this->context->massTagQuery);
			$this->renderExternal('input-text', $context);
		?>

		<?php
			$context = new StdClass;
			$context->name = 'tag';
			$context->label = 'Tag';
			$context->inputClass = 'autocomplete';
			if (isset($this->context->massTagTag))
				$context->value = htmlspecialchars($this->context->massTagTag);
			$this->renderExternal('input-text', $context);

			if (isset($this->context->transport->paginator))
			{
				$context = new StdClass;
				$context->name = 'old-page';
				$context->value = intval($this->context->transport->paginator->page);
				$this->renderExternal('input-hidden', $context);
			}

			if (isset($this->context->massTagQuery))
			{
				$context = new StdClass;
				$context->name = 'old-query';
				$context->value = htmlspecialchars($this->context->massTagQuery);
				$this->renderExternal('input-hidden', $context);
			}
		?>

		<div class="form-row">
			<label></label>
			<button class="submit" type="submit">Tag!</button>
		</div>
	</form>
</div>
