<div class="form-wrapper">
	<form method="post" action="<?= \Chibi\Router::linkTo(
		['PostController', 'listRedirectAction'],
		['source' => 'mass-tag']) ?>">
		<h1>mass tag</h1>

		<div class="form-row">
			<label for="mass-tag-query">Search query:</label>
			<div class="input-wrapper">
				<input
					class="autocomplete"
					type="text"
					name="query"
					id="mass-tag-query"
					value="<?= isset($this->context->massTagQuery)
						? htmlspecialchars($this->context->massTagQuery)
						: '' ?>"/>
			</div>
		</div>

		<div class="form-row">
			<label for="mass-tag-tag">Tag:</label>
			<div class="input-wrapper">
				<input
					class="autocomplete"
					type="text"
					name="tag"
					id="mass-tag-tag"
					value="<?= isset($this->context->massTagTag)
						? htmlspecialchars($this->context->massTagTag)
						: '' ?>"/>
			</div>
		</div>

		<input
			type="hidden"
			name="old-page"
			value="<?= isset($this->context->transport->paginator)
				? htmlspecialchars($this->context->transport->paginator->page)
				: '' ?>"/>

		<input
			type="hidden"
			name="old-query"
			value="<?= isset($this->context->massTagQuery)
				? htmlspecialchars($this->context->massTagQuery)
				: '' ?>"/>

		<div class="form-row">
			<label></label>
			<button class="submit" type="submit">Tag!</button>
		</div>
	</form>
</div>
